# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^.serverless/
    -   id: check-json
    -   id: check-ast
    -   id: check-added-large-files
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: flake8
